# Generated by Django 4.2 on 2023-04-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('omens', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
